/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.firebase.database;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int buttonSize = 0x7f040056;
        public static final int circleCrop = 0x7f04007b;
        public static final int colorScheme = 0x7f040092;
        public static final int font = 0x7f0400da;
        public static final int fontProviderAuthority = 0x7f0400dc;
        public static final int fontProviderCerts = 0x7f0400dd;
        public static final int fontProviderFetchStrategy = 0x7f0400de;
        public static final int fontProviderFetchTimeout = 0x7f0400df;
        public static final int fontProviderPackage = 0x7f0400e0;
        public static final int fontProviderQuery = 0x7f0400e1;
        public static final int fontStyle = 0x7f0400e2;
        public static final int fontWeight = 0x7f0400e4;
        public static final int imageAspectRatio = 0x7f0400ff;
        public static final int imageAspectRatioAdjust = 0x7f040100;
        public static final int scopeUris = 0x7f04019e;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f050000;
    }
    public static final class color {
        private color() {}

        public static final int common_google_signin_btn_text_dark = 0x7f060031;
        public static final int common_google_signin_btn_text_dark_default = 0x7f060032;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f060033;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f060034;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f060035;
        public static final int common_google_signin_btn_text_light = 0x7f060036;
        public static final int common_google_signin_btn_text_light_default = 0x7f060037;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f060038;
        public static final int common_g